#include "x/test.h"
#include "x/regex.h"
#include "x/types.h"

static int result;
static x_recatch c;
static char str[1024];
#define RETVAL_TEST(text, re, n) { \
	result = x_rematch(text, re, &c); \
	ut_assert_int_equal(r, n, result); \
}
#define FETCH_TEST(text, re, n, rtext) { \
	x_rematch(text, re, &c); \
	ut_assert_str_equal(r, x_recatch_fetch(&c, str, n), rtext); \
}
#define PUT_TEST(text, re, rtext, ctext) { \
	x_rematch(text, re, &c); \
	ut_assert_str_equal(r, ctext, x_recatch_put(&c, str, rtext)); \
}
#define REPLACE_TEST(text, re, n, rtext, ctext) { \
	x_rematch(text, re, &c); \
	ut_assert_str_equal(r, ctext, x_recatch_replace(&c, str, rtext, n)); \
}

static void retcode(ut_runner *r)
{
	RETVAL_TEST("ab", "a(b|c)|A(B|C)", 1);
	RETVAL_TEST("ac", "a(b|c)|A(B|C)", 1);
	RETVAL_TEST("AB", "a(b|c)|A(B|C)", 1);
	RETVAL_TEST("AC", "a(b|c)|A(B|C)", 1);
	RETVAL_TEST("ab", "a<b|c>|A<B|C>", 1);
	RETVAL_TEST("ac", "a<b|c>|A<B|C>", 1);
	RETVAL_TEST("AB", "a<b|c>|A<B|C>", 1);
	RETVAL_TEST("AC", "a<b|c>|A<B|C>", 1);
	RETVAL_TEST("ab"    , "(a(b|c)|A(B|C))|1234(ea|eb|ec)", 1);
	RETVAL_TEST("ac"    , "(a(b|c)|A(B|C))|1234(ea|eb|ec)", 1);
	RETVAL_TEST("AC"    , "(a(b|c)|A(B|C))|1234(ea|eb|ec)", 1);
	RETVAL_TEST("ab"    , "<a<b|c>|A<B|C>>|1234<ea|eb|ec>", 1);
	RETVAL_TEST("ac"    , "<a<b|c>|A<B|C>>|1234<ea|eb|ec>", 1);
	RETVAL_TEST("AC"    , "<a<b|c>|A<B|C>>|1234<ea|eb|ec>", 1);
	RETVAL_TEST("1234eb", "(a(b|c)|A(B|C))|1234(ea|eb|ec)", 1);
	RETVAL_TEST("1234ec", "(a(b|c)|A(B|C))|1234(ea|eb|ec)", 1);
	RETVAL_TEST("1234eb", "<a<b|c>|A<B|C>>|1234<ea|eb|ec>", 1);
	RETVAL_TEST("1234ec", "<a<b|c>|A<B|C>>|1234<ea|eb|ec>", 1);
	RETVAL_TEST("1234ec", "(a<b|c>|A<B|C>)|1234(ea|eb|ec)", 1);
	RETVAL_TEST("1234eb", "<a(b|c)|A(B|C)>|1234(ea|eb|ec)", 1);
	RETVAL_TEST("1234ec", "(a<b|c>|A(B|C))|1234<ea|eb|ec>", 1);
	RETVAL_TEST("ace", "a(b|c)(d|e)|A(B|C)(D|E)", 1);
	RETVAL_TEST("ABD", "a(b|c)(d|e)|A(B|C)(D|E)", 1);
	RETVAL_TEST("ace", "a<b|c><d|e>|A<B|C><D|E>", 1);
	RETVAL_TEST("ABD", "a<b|c><d|e>|A<B|C><D|E>", 1);

	RETVAL_TEST("ABC", "#^A", 1);
	RETVAL_TEST("ABC", "#^AB", 1);
	RETVAL_TEST("ABC", "#^ABC", 1);
	RETVAL_TEST("ABC", "#^(b|A)", 1);
	RETVAL_TEST("ABC", "#^A(B|C)(B|C)", 1);
	RETVAL_TEST("ABC", "#^(A(B|C))(B|C)", 1);
	RETVAL_TEST("ABC", "#$C", 1);
	RETVAL_TEST("ABC", "#$BC", 1);
	RETVAL_TEST("ABC", "#$ABC", 1);
	RETVAL_TEST("ABC", "#$(b|C)", 1);
	RETVAL_TEST("ABC", "#$A(B|C)(B|C)", 1);
	RETVAL_TEST("ABC", "#$(A(B|C))(B|C)", 1);
	RETVAL_TEST("ABC", "#^$ABC", 1);
	RETVAL_TEST("ABC", "#^$A(c|B)(b|C)", 1);
	RETVAL_TEST("ABC", "#^$A(B|C)(B|C)", 1);
	RETVAL_TEST("ABC", "#^$(A(B|C))(B|C)", 1);


	RETVAL_TEST("ab", "", 0);
	RETVAL_TEST("ab", "a|", 1);
	// RETVAL_TEST("ab", "|", 0);
	RETVAL_TEST("ab", "()", 0);
	// RETVAL_TEST("ab", "|()", 0);
	RETVAL_TEST("ab", "()|", 0);
	//RETVAL_TEST("ab", "(|)", 0);
	RETVAL_TEST("ab", "()|()", 0);
	// RETVAL_TEST("ab", "(|)|(|)", 0);
	RETVAL_TEST("", "a", 0);
	RETVAL_TEST("", "a|", 0);
	RETVAL_TEST("", "a|b", 0);
	RETVAL_TEST("", "a(b)c", 0);
	RETVAL_TEST("", "raptor|(test)", 0);
	RETVAL_TEST("", "|()", 0);
	RETVAL_TEST("", "()|", 0);
	RETVAL_TEST("", "(|)", 0);
	RETVAL_TEST("", "()|()", 0);
	RETVAL_TEST("", "(|)|(|)", 0);
	RETVAL_TEST("ax", "a(b|c)|A(B|C)", 0);
	RETVAL_TEST("ax", "a(b|c)|A(B|C)", 0);
	RETVAL_TEST("Ax", "a(b|c)|A(B|C)", 0);
	RETVAL_TEST("Ax", "a(b|c)|A(B|C)", 0);

	RETVAL_TEST("ABC", "#^E", 0);
	RETVAL_TEST("ABC", "#^EB", 0);
	RETVAL_TEST("ABC", "#^EBC", 0);
	RETVAL_TEST("ABC", "#^(b|E)", 0);
	RETVAL_TEST("ABC", "#^A(B|C)(B|E)", 0);
	RETVAL_TEST("ABC", "#^(A(B|C))(B|E)", 0);
	RETVAL_TEST("ABC", "#$E", 0);
	RETVAL_TEST("ABC", "#$BE", 0);
	RETVAL_TEST("ABC", "#$ABE", 0);
	RETVAL_TEST("ABC", "#$(b|E)", 0);
	RETVAL_TEST("ABC", "#$A(B|C)(B|E)", 0);
	RETVAL_TEST("ABC", "#$(A(B|C))(B|E)", 0);
	RETVAL_TEST("ABC", "#^$ABE", 0);
	RETVAL_TEST("ABC", "#^$A(c|B)(b|E)", 0);
	RETVAL_TEST("ABC", "#^$A(B|C)(B|E)", 0);
	RETVAL_TEST("ABC", "#^$(A(B|C))(B|E)", 0);

	// RETVAL_TEST("",  "",  0);
	RETVAL_TEST("", "a",  0);
	RETVAL_TEST("a", "",  0);
	RETVAL_TEST("a", "o", 0);
	RETVAL_TEST("a", "a", 1);
	RETVAL_TEST("a", "()", 0);
	RETVAL_TEST("a", "()|", 0);
	// RETVAL_TEST("a", "|()", 0);
	// RETVAL_TEST("a", "(|)", 0);
	RETVAL_TEST("aaa", "a", 3);
	RETVAL_TEST("a", "aaa", 0);
	RETVAL_TEST("a", "a()a", 0);
	RETVAL_TEST("a aaa aaa", "aaa", 2);
	RETVAL_TEST("Raptor Test", "a", 1);
	RETVAL_TEST("Raptor Test", "t", 2);
	RETVAL_TEST("aeiou", "a|e|i|o|u", 5);
	RETVAL_TEST("aeiou", "(a|e|i|o|u)", 5);
	RETVAL_TEST("aeiou", "(a|e)|i|(o|u)", 5);
	RETVAL_TEST("aeiou", "(a|(e))|(i|(o|u))", 5);
	RETVAL_TEST("aa ae ai ao au", "a(a|e|i|o|u)", 5);
	RETVAL_TEST("aa ae ai ao au", "a(0|1|2|3|4)", 0);
	RETVAL_TEST("aa ae ai ao au", "a(a|e|i|o|u) ", 4);
	RETVAL_TEST("aa ae Ai ao au", "A(a|e|i|o|u)", 1);
	RETVAL_TEST("aa ae Ai ao au", "(A|a)(a|e|i|o|u)", 5);
	RETVAL_TEST("aae aei Aio aoa auu", "(A|a)(a|e|i|o|u)(a|e|i|o|u)", 5);

	RETVAL_TEST("a aaa aaa", "#^aaa", 0);
	RETVAL_TEST("a aaa aaa", "#$aaa", 1);
	RETVAL_TEST("a aaa aaa", "#?aaa", 1);
	RETVAL_TEST("a aaa aaa", "#~aaa", 2);
	RETVAL_TEST("a aaa aaa", "#^?aaa", 0);
	RETVAL_TEST("a aaa aaa", "#?^aaa", 0);
	RETVAL_TEST("a aaa aaa", "#^?$aaa", 0);
	RETVAL_TEST("a aaa aaa", "#?$^aaa", 0);
	RETVAL_TEST("a aaa aaa", "#^?$a aaa aaa", 1);
	RETVAL_TEST("aa aaaa aaaa", "a", 10);
	RETVAL_TEST("aa aaaa aaaa", "#~a", 10);
	RETVAL_TEST("aa aaaa aaaa", "aa", 5);
	RETVAL_TEST("aa aaaa aaaa", "#~aa", 7);
	RETVAL_TEST("aa aaaa aaaa", "aaa", 2);
	RETVAL_TEST("aa aaaa aaaa", "#~aaa", 4);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a", 20);
	RETVAL_TEST("abababababababababababababababababababab", "a"  , 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "(a)", 20);
	RETVAL_TEST("abababababababababababababababababababab", "(a)", 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "<a>", 20);
	RETVAL_TEST("abababababababababababababababababababab", "<a>", 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a+",   1);
	RETVAL_TEST("abababababababababababababababababababab", "a+" , 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "#?a+", 1);
	RETVAL_TEST("abababababababababababababababababababab", "#?a+" , 1);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "#~a+", 20);
	RETVAL_TEST("abababababababababababababababababababab", "#~a+" , 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a?", 20);
	RETVAL_TEST("abababababababababababababababababababab", "a?" , 40);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a*", 1);
	RETVAL_TEST("abababababababababababababababababababab", "a*" , 40);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{1}", 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{1}", 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{5}", 4);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{1,5}", 4);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{5,5}", 4);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{10}", 2);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{1,100}", 1);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{001,00100}", 1);
	RETVAL_TEST("abababababababababababababababababababab", "a{1}" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "a{001}" , 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{1,1}", 20);
	RETVAL_TEST("abababababababababababababababababababab", "a{1,1}" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "a{001,000001}" , 20);
	RETVAL_TEST("aaaaaaaaaaaaaaaaaaaa", "a{20}", 1);
	RETVAL_TEST("abababababababababababababababababababab", "(a|b){1,1}" , 40);

	RETVAL_TEST("abc", "<b>", 1);
	RETVAL_TEST("abc", "a<b>", 1);
	RETVAL_TEST("abc", "<b>c", 1);
	RETVAL_TEST("abc", "a<b>c", 1);
	RETVAL_TEST("abc", "<a|b>", 2);
	RETVAL_TEST("abc", "<a|b|c>", 3);
	RETVAL_TEST("abc", "<(a|b)|c>", 3);
	RETVAL_TEST("abc", "#~<a|b|c>", 3);
	RETVAL_TEST("abc", "#~<ab|c>", 2);
	RETVAL_TEST("aa aaaa aaaa", "<aa>", 5);
	RETVAL_TEST("aa aaaa aaaa", "#~<aa>", 7);
	RETVAL_TEST("abc", "a<x>", 0);
	RETVAL_TEST("abc", "<a>x", 0);
	RETVAL_TEST("abc", "<a|b>x", 0);
	RETVAL_TEST("abc", "<<a|b>x|abc>", 1);
	RETVAL_TEST("abc", "<x<a|b>|abc>", 1);
	RETVAL_TEST("abc abc abc", "<a|b|c>", 9);
	RETVAL_TEST("abc abc abc", "<(a|b|c)(a|b|c)(a|b|c)>", 3);
	RETVAL_TEST("abc abc abc", "<(a|b|c)(a|b|c)(a|b|c)> ", 2);
	RETVAL_TEST("abc abc abc", "#?<(a|b|c)(a|b|c)(a|b|c)>", 1);
	RETVAL_TEST("abc abc abc", "#?<(a|b|c)(a|b|c)((a|b)|x)>", 0);
	RETVAL_TEST("abc abc abx", "#?<(a|b|c)(a|b|c)((a|b)|x)>", 1);
	RETVAL_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 3);

	RETVAL_TEST("a", "a?", 1);
	RETVAL_TEST("a", "b?", 1);
	RETVAL_TEST("a", "a+", 1);
	RETVAL_TEST("a", "a*", 1);
	RETVAL_TEST("a", "b*", 1);
	RETVAL_TEST("a", "aa?", 1);
	RETVAL_TEST("a", "ab?", 1);
	RETVAL_TEST("a", "aa+", 0);
	RETVAL_TEST("a", "aa*", 1);
	RETVAL_TEST("a", "ab*", 1);
	RETVAL_TEST("a", "a{1,2}", 1);
	RETVAL_TEST("aaa", "a+", 1);
	RETVAL_TEST("aaa", "a*", 1);
	RETVAL_TEST("aaa", "a+", 1);
	RETVAL_TEST("aaa", "a?", 3);
	RETVAL_TEST("aaab", "a+", 1);
	RETVAL_TEST("aaab", "a*", 2);
	RETVAL_TEST("aaab", "a?", 4);
	RETVAL_TEST("aaab", "a+b", 1);
	RETVAL_TEST("aaab", "a*b", 1);
	RETVAL_TEST("aaab", "a?b", 1);
	RETVAL_TEST("aaab", "a+b?", 1);
	RETVAL_TEST("aaab", "a*b?", 1);
	RETVAL_TEST("aaab", "a?b?", 3);
	RETVAL_TEST("aaab", "a+b+", 1);
	RETVAL_TEST("aaab", "a*b+", 1);
	RETVAL_TEST("aaab", "a?b+", 1);
	RETVAL_TEST("aaab", "a+b*", 1);
	RETVAL_TEST("aaab", "a*b*", 1);
	RETVAL_TEST("aaab", "a?b*", 3);
	RETVAL_TEST("aaabaaa", "a+", 2);
	RETVAL_TEST("aaabaaa", "a*", 3);
	RETVAL_TEST("aaabaaa", "a*", 3);
	RETVAL_TEST("aaabaaa", "a*", 3);
	RETVAL_TEST("a", "(a)?", 1);
	RETVAL_TEST("a", "(b)?", 1);
	RETVAL_TEST("a", "(a)+", 1);
	RETVAL_TEST("a", "(a)*", 1);
	RETVAL_TEST("a", "(b)*", 1);
	RETVAL_TEST("aaa", "(a)+", 1);
	RETVAL_TEST("aaa", "(a)*", 1);
	RETVAL_TEST("aaa", "#~(a)+", 3);
	RETVAL_TEST("aaa", "#~(a)*", 3);
	RETVAL_TEST("aaab", "#~(a+)", 3);
	RETVAL_TEST("aaab", "#~(a*)", 4);
	RETVAL_TEST("aaab", "#~(a?)", 4);
	RETVAL_TEST("aaab", "#~(a+b)", 3);
	RETVAL_TEST("aaab", "#~(a*b)", 4);
	RETVAL_TEST("aaab", "#~(a?b)", 2);
	RETVAL_TEST("aaab", "#~(a+b?)", 3);
	RETVAL_TEST("aaab", "#~(a*b?)", 4);
	RETVAL_TEST("aaab", "#~(a?b?)", 4);
	RETVAL_TEST("aaab", "#~(a+b+)", 3);
	RETVAL_TEST("aaab", "#~(a*b+)", 4);
	RETVAL_TEST("aaab", "#~(a?b+)", 2);
	RETVAL_TEST("aaab", "#~(a+b*)", 3);
	RETVAL_TEST("aaab", "#~(a*b*)", 4);
	RETVAL_TEST("aaab", "#~(a?b*)", 4);
	RETVAL_TEST("aaabaaa", "#~(a+)", 6);
	RETVAL_TEST("aaabaaa", "#~(a*)", 7);

	RETVAL_TEST("Raptor Test",     "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Raaaaptor TFest", "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("CaptorTest",      "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Cap CaptorTest",  "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Rap Captor Fest", "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Raptor Test",     "#^$<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Raaaaptor TFest", "#^$<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("CaptorTest",      "#^$<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Cap CaptorTest",  "#^$<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Rap Captor Fest", "#^$<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Raptor Test",     "#~?<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Raaaaptor TFest", "#~?<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("CaptorTest",      "#~?<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Cap CaptorTest",  "#~?<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);
	RETVAL_TEST("Rap Captor Fest", "#~?<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1);

	RETVAL_TEST("a", ":a", 1);
	RETVAL_TEST("a", ":A", 0);
	RETVAL_TEST("a", ":d", 0);
	RETVAL_TEST("a", ":D", 1);
	RETVAL_TEST("a", ":w", 1);
	RETVAL_TEST("a", ":W", 0);
	RETVAL_TEST("a", ":s", 0);
	RETVAL_TEST("a", ":S", 1);
	RETVAL_TEST("A", ":a", 1);
	RETVAL_TEST("A", ":A", 0);
	RETVAL_TEST("A", ":d", 0);
	RETVAL_TEST("A", ":D", 1);
	RETVAL_TEST("A", ":w", 1);
	RETVAL_TEST("A", ":W", 0);
	RETVAL_TEST("A", ":s", 0);
	RETVAL_TEST("A", ":S", 1);
	RETVAL_TEST("4", ":a", 0);
	RETVAL_TEST("4", ":A", 1);
	RETVAL_TEST("4", ":d", 1);
	RETVAL_TEST("4", ":D", 0);
	RETVAL_TEST("4", ":w", 1);
	RETVAL_TEST("4", ":W", 0);
	RETVAL_TEST("4", ":s", 0);
	RETVAL_TEST("4", ":S", 1);
	RETVAL_TEST(" ", ":a", 0);
	RETVAL_TEST(" ", ":A", 1);
	RETVAL_TEST(" ", ":d", 0);
	RETVAL_TEST(" ", ":D", 1);
	RETVAL_TEST(" ", ":w", 0);
	RETVAL_TEST(" ", ":W", 1);
	RETVAL_TEST(" ", ":s", 1);
	RETVAL_TEST(" ", ":S", 0);
	RETVAL_TEST("\t", ":a", 0);
	RETVAL_TEST("\t", ":A", 1);
	RETVAL_TEST("\t", ":d", 0);
	RETVAL_TEST("\t", ":D", 1);
	RETVAL_TEST("\t", ":w", 0);
	RETVAL_TEST("\t", ":W", 1);
	RETVAL_TEST("\t", ":s", 1);
	RETVAL_TEST("\t", ":S", 0);

	RETVAL_TEST("eee", ":a", 3);
	RETVAL_TEST("aaa", ":A", 0);
	RETVAL_TEST("aaa", ":d", 0);
	RETVAL_TEST("aaa", ":D", 3);
	RETVAL_TEST("aaa", ":w", 3);
	RETVAL_TEST("aaa", ":W", 0);
	RETVAL_TEST("aaa", ":s", 0);
	RETVAL_TEST("aaa", ":S", 3);
	RETVAL_TEST("AAA", ":a", 3);
	RETVAL_TEST("AAA", ":A", 0);
	RETVAL_TEST("AAA", ":d", 0);
	RETVAL_TEST("AAA", ":D", 3);
	RETVAL_TEST("AAA", ":w", 3);
	RETVAL_TEST("AAA", ":W", 0);
	RETVAL_TEST("AAA", ":s", 0);
	RETVAL_TEST("AAA", ":S", 3);
	RETVAL_TEST("444", ":a", 0);
	RETVAL_TEST("444", ":A", 3);
	RETVAL_TEST("444", ":d", 3);
	RETVAL_TEST("444", ":D", 0);
	RETVAL_TEST("444", ":w", 3);
	RETVAL_TEST("444", ":W", 0);
	RETVAL_TEST("444", ":s", 0);
	RETVAL_TEST("444", ":S", 3);
	RETVAL_TEST("   ", ":a", 0);
	RETVAL_TEST("   ", ":A", 3);
	RETVAL_TEST("   ", ":d", 0);
	RETVAL_TEST("   ", ":D", 3);
	RETVAL_TEST("   ", ":w", 0);
	RETVAL_TEST("   ", ":W", 3);
	RETVAL_TEST("   ", ":s", 3);
	RETVAL_TEST("   ", ":S", 0);
	RETVAL_TEST("\t\t\t", ":a", 0);
	RETVAL_TEST("\t\t\t", ":A", 3);
	RETVAL_TEST("\t\t\t", ":d", 0);
	RETVAL_TEST("\t\t\t", ":D", 3);
	RETVAL_TEST("\t\t\t", ":w", 0);
	RETVAL_TEST("\t\t\t", ":W", 3);
	RETVAL_TEST("\t\t\t", ":s", 3);
	RETVAL_TEST("\t\t\t", ":S", 0);

	RETVAL_TEST("eee", ":a+", 1);
	RETVAL_TEST("aaa", ":A+", 0);
	RETVAL_TEST("aaa", ":d+", 0);
	RETVAL_TEST("aaa", ":D+", 1);
	RETVAL_TEST("aaa", ":w+", 1);
	RETVAL_TEST("aaa", ":W+", 0);
	RETVAL_TEST("aaa", ":s+", 0);
	RETVAL_TEST("aaa", ":S+", 1);
	RETVAL_TEST("AAA", ":a+", 1);
	RETVAL_TEST("AAA", ":A+", 0);
	RETVAL_TEST("AAA", ":d+", 0);
	RETVAL_TEST("AAA", ":D+", 1);
	RETVAL_TEST("AAA", ":w+", 1);
	RETVAL_TEST("AAA", ":W+", 0);
	RETVAL_TEST("AAA", ":s+", 0);
	RETVAL_TEST("AAA", ":S+", 1);
	RETVAL_TEST("444", ":a+", 0);
	RETVAL_TEST("444", ":A+", 1);
	RETVAL_TEST("444", ":d+", 1);
	RETVAL_TEST("444", ":D+", 0);
	RETVAL_TEST("444", ":w+", 1);
	RETVAL_TEST("444", ":W+", 0);
	RETVAL_TEST("444", ":s+", 0);
	RETVAL_TEST("444", ":S+", 1);
	RETVAL_TEST("   ", ":a+", 0);
	RETVAL_TEST("   ", ":A+", 1);
	RETVAL_TEST("   ", ":d+", 0);
	RETVAL_TEST("   ", ":D+", 1);
	RETVAL_TEST("   ", ":w+", 0);
	RETVAL_TEST("   ", ":W+", 1);
	RETVAL_TEST("   ", ":s+", 1);
	RETVAL_TEST("   ", ":S+", 0);
	RETVAL_TEST("\t\t\t", ":a+", 0);
	RETVAL_TEST("\t\t\t", ":A+", 1);
	RETVAL_TEST("\t\t\t", ":d+", 0);
	RETVAL_TEST("\t\t\t", ":D+", 1);
	RETVAL_TEST("\t\t\t", ":w+", 0);
	RETVAL_TEST("\t\t\t", ":W+", 1);
	RETVAL_TEST("\t\t\t", ":s+", 1);
	RETVAL_TEST("\t\t\t", ":S+", 0);

	RETVAL_TEST("eee", "#~:a+", 3);
	RETVAL_TEST("aaa", "#~:A+", 0);
	RETVAL_TEST("aaa", "#~:d+", 0);
	RETVAL_TEST("aaa", "#~:D+", 3);
	RETVAL_TEST("aaa", "#~:w+", 3);
	RETVAL_TEST("aaa", "#~:W+", 0);
	RETVAL_TEST("aaa", "#~:s+", 0);
	RETVAL_TEST("aaa", "#~:S+", 3);
	RETVAL_TEST("AAA", "#~:a+", 3);
	RETVAL_TEST("AAA", "#~:A+", 0);
	RETVAL_TEST("AAA", "#~:d+", 0);
	RETVAL_TEST("AAA", "#~:D+", 3);
	RETVAL_TEST("AAA", "#~:w+", 3);
	RETVAL_TEST("AAA", "#~:W+", 0);
	RETVAL_TEST("AAA", "#~:s+", 0);
	RETVAL_TEST("AAA", "#~:S+", 3);
	RETVAL_TEST("444", "#~:a+", 0);
	RETVAL_TEST("444", "#~:A+", 3);
	RETVAL_TEST("444", "#~:d+", 3);
	RETVAL_TEST("444", "#~:D+", 0);
	RETVAL_TEST("444", "#~:w+", 3);
	RETVAL_TEST("444", "#~:W+", 0);
	RETVAL_TEST("444", "#~:s+", 0);
	RETVAL_TEST("444", "#~:S+", 3);
	RETVAL_TEST("   ", "#~:a+", 0);
	RETVAL_TEST("   ", "#~:A+", 3);
	RETVAL_TEST("   ", "#~:d+", 0);
	RETVAL_TEST("   ", "#~:D+", 3);
	RETVAL_TEST("   ", "#~:w+", 0);
	RETVAL_TEST("   ", "#~:W+", 3);
	RETVAL_TEST("   ", "#~:s+", 3);
	RETVAL_TEST("   ", "#~:S+", 0);
	RETVAL_TEST("\t\t\t", "#~:a+", 0);
	RETVAL_TEST("\t\t\t", "#~:A+", 3);
	RETVAL_TEST("\t\t\t", "#~:d+", 0);
	RETVAL_TEST("\t\t\t", "#~:D+", 3);
	RETVAL_TEST("\t\t\t", "#~:w+", 0);
	RETVAL_TEST("\t\t\t", "#~:W+", 3);
	RETVAL_TEST("\t\t\t", "#~:s+", 3);
	RETVAL_TEST("\t\t\t", "#~:S+", 0);

	RETVAL_TEST("aeiou", ":a", 5);

	RETVAL_TEST("(((", ":(", 3);
	RETVAL_TEST(")))", ":)", 3);
	RETVAL_TEST("<<<", ":<", 3);
	RETVAL_TEST(">>>", ":>", 3);
	RETVAL_TEST(":::", "::", 3);
	RETVAL_TEST("|||", ":|", 3);
	RETVAL_TEST("###", ":#", 3);
	RETVAL_TEST(":#()|<>", ":::#:(:):|:<:>", 1);
	RETVAL_TEST(":#()|<>", "(::|:#|:(|:)|:||:<|:>)", 7);
	RETVAL_TEST("(test1)(test2)", ":(test:d:)", 2);

	RETVAL_TEST("",  ".",  0);
	RETVAL_TEST("a", ".",  1);
	RETVAL_TEST("aaa", ".", 3);
	RETVAL_TEST("a", "...", 0);
	RETVAL_TEST("a aaa aaa", ".", 9);
	RETVAL_TEST("a aaa aaa", "...", 3);
	RETVAL_TEST("a aaa aaa", ".aa", 2);
	RETVAL_TEST("a aaa aaa", "aa.", 2);
	RETVAL_TEST("Raptor Test", ".a", 1);
	RETVAL_TEST("Raptor Test", ".t", 2);
	RETVAL_TEST("Raptor Test", ".z", 0);
	RETVAL_TEST("Raptor Test", "a.", 1);
	RETVAL_TEST("Raptor Test", " .", 1);
	RETVAL_TEST("Raptor Test", "z.", 0);
	RETVAL_TEST("a", ".?", 1);
	RETVAL_TEST("a", ".+", 1);
	RETVAL_TEST("a", ".*", 1);
	RETVAL_TEST("a", ".{1}", 1);
	RETVAL_TEST("a aaa aaa", ".?", 9);
	RETVAL_TEST("a aaa aaa", ".+", 1);
	RETVAL_TEST("a aaa aaa", ".*", 1);
	RETVAL_TEST("a aaa aaa", ".{1}", 9);
	RETVAL_TEST("a", "a.?", 1);
	RETVAL_TEST("a", "a.+", 0);
	RETVAL_TEST("a", "a.*", 1);
	RETVAL_TEST("a", "a.{1}", 0);
	RETVAL_TEST("aeiou", "a|.", 5);
	RETVAL_TEST("aeiou", "a|.?", 5);
	RETVAL_TEST("aeiou", "a|.+", 2);
	RETVAL_TEST("aeiou", "a|.*", 2);
	RETVAL_TEST("aeiou", ".|a", 5);
	RETVAL_TEST("aeiou", ".?|a", 5);
	RETVAL_TEST("aeiou", ".+|a", 1);
	RETVAL_TEST("aeiou", ".*|a", 1);
	RETVAL_TEST("aeiou", "(a|.)", 5);
	RETVAL_TEST("aeiou", "(a|.?)", 5);
	RETVAL_TEST("aeiou", "(a|.+)", 2);
	RETVAL_TEST("aeiou", "(a|.*)", 2);
	RETVAL_TEST("aeiou", "(.|a)", 5);
	RETVAL_TEST("aeiou", "(.?|a)", 5);
	RETVAL_TEST("aeiou", "(.+|a)", 1);
	RETVAL_TEST("aeiou", "(.*|a)", 1);
	RETVAL_TEST("aeiou", "a|(.)", 5);
	RETVAL_TEST("aeiou", "a|(.?)", 5);
	RETVAL_TEST("aeiou", "a|(.+)", 2);
	RETVAL_TEST("aeiou", "a|(.*)", 2);
	RETVAL_TEST("aeiou", "(.)|a", 5);
	RETVAL_TEST("aeiou", "(.?)|a", 5);
	RETVAL_TEST("aeiou", "(.+)|a", 1);
	RETVAL_TEST("aeiou", "(.*)|a", 1);
	RETVAL_TEST("aeiou", "a|(.)", 5);
	RETVAL_TEST("aeiou", "a|(.)?", 5);
	RETVAL_TEST("aeiou", "a|(.)+", 2);
	RETVAL_TEST("aeiou", "a|(.)*", 2);
	RETVAL_TEST("aeiou", "(.)|a", 5);
	RETVAL_TEST("aeiou", "(.)?|a", 5);
	RETVAL_TEST("aeiou", "(.)+|a", 1);
	RETVAL_TEST("aeiou", "(.)*|a", 1);
	RETVAL_TEST("abababababababababababababababababababab", "(a.)" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "(.a)" , 19);
	RETVAL_TEST("abababababababababababababababababababab", "(:a.)" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "(.:a)" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "(.{5}:a{5})" , 4);

	RETVAL_TEST("",  "[a]",  0);
	RETVAL_TEST("a", "[a]",  1);
	RETVAL_TEST("a", "[.]",  0);
	RETVAL_TEST(".", "[.]",  1);
	RETVAL_TEST("a", "[A]",  0);
	RETVAL_TEST("A", "[A]",  1);
	RETVAL_TEST("1", "[A]",  0);
	RETVAL_TEST("1", "[1]",  1);
	RETVAL_TEST("a", "[:a]", 1);
	RETVAL_TEST("A", "[:D]", 1);
	RETVAL_TEST("aaa", "[a-z]", 3);
	RETVAL_TEST("...", "[.]",  3);
	RETVAL_TEST("a", "[a-z][a-z][a-z]", 0);
	RETVAL_TEST("a aaa aaa", "[a-z]", 7);
	RETVAL_TEST("a aaa aaa", "[ a-z]", 9);
	RETVAL_TEST("a aaa aaa", "[a-z][a-z][a-z]", 2);
	RETVAL_TEST("a aaa aaa", "[a-z]aa", 2);
	RETVAL_TEST("a aaa aaa", "aa[a-z]", 2);
	RETVAL_TEST("Raptor Test", "[:w]a", 1);
	RETVAL_TEST("Raptor Test", "[:w]t", 2);
	RETVAL_TEST("Raptor Test", "[a-z]z", 0);
	RETVAL_TEST("Raptor Test", "a[a-z]", 1);
	RETVAL_TEST("Raptor Test", " [A-Z]", 1);
	RETVAL_TEST("Raptor Test", "z[a-z]", 0);
	RETVAL_TEST("a", "[a]?", 1);
	RETVAL_TEST("a", "[a]+", 1);
	RETVAL_TEST("a", "[a]*", 1);
	RETVAL_TEST("a", "[a]{1}", 1);
	RETVAL_TEST("a aaa aaa", "[a-z]?", 9);
	RETVAL_TEST("a aaa aaa", "[a-z]+", 3);
	RETVAL_TEST("a aaa aaa", "[a-z]*", 5);
	RETVAL_TEST("a aaa aaa", "[a-z]{1}", 7);
	RETVAL_TEST("....", "[.]{1}", 4);
	RETVAL_TEST(".{4}", "[.{4}]{1}", 4);
	RETVAL_TEST("}.{4", "[.{4}]{1}", 4);
	RETVAL_TEST("a", "a[a-z]?", 1);
	RETVAL_TEST("a", "a[a-z]+", 0);
	RETVAL_TEST("a", "a[a-z]*", 1);
	RETVAL_TEST("a", "a[a-z]{1}", 0);
	RETVAL_TEST("aeiou", "a|[aeiou]", 5);
	RETVAL_TEST("aeiou", "a|[aeiou]?", 5);
	RETVAL_TEST("aeiou", "a|[aeiou]+", 2);
	RETVAL_TEST("aeiou", "a|[aeiou]*", 2);
	RETVAL_TEST("aeiou", "[aeiou]|a", 5);
	RETVAL_TEST("aeiou", "[aeiou]?|a", 5);
	RETVAL_TEST("aeiou", "[aeiou]+|a", 1);
	RETVAL_TEST("aeiou", "[aeiou]*|a", 1);
	RETVAL_TEST("aeiou", "(a|[aeiou])", 5);
	RETVAL_TEST("aeiou", "(a|[aeiou]?)", 5);
	RETVAL_TEST("aeiou", "(a|[aeiou]+)", 2);
	RETVAL_TEST("aeiou", "(a|[aeiou]*)", 2);
	RETVAL_TEST("aeiou", "([aeiou]|a)", 5);
	RETVAL_TEST("aeiou", "([aeiou]?|a)", 5);
	RETVAL_TEST("aeiou", "([aeiou]+|a)", 1);
	RETVAL_TEST("aeiou", "([aeiou]*|a)", 1);
	RETVAL_TEST("aeiou", "a|([aeiou])", 5);
	RETVAL_TEST("aeiou", "a|([aeiou]?)", 5);
	RETVAL_TEST("aeiou", "a|([aeiou]+)", 2);
	RETVAL_TEST("aeiou", "a|([aeiou]*)", 2);
	RETVAL_TEST("aeiou", "([aeiou])|a", 5);
	RETVAL_TEST("aeiou", "([aeiou]?)|a", 5);
	RETVAL_TEST("aeiou", "([aeiou]+)|a", 1);
	RETVAL_TEST("aeiou", "([aeiou]*)|a", 1);
	RETVAL_TEST("aeiou", "a|([aeiou])", 5);
	RETVAL_TEST("aeiou", "a|([aeiou])?", 5);
	RETVAL_TEST("aeiou", "a|([aeiou])+", 2);
	RETVAL_TEST("aeiou", "a|([aeiou])*", 2);
	RETVAL_TEST("aeiou", "([aeiou])|a", 5);
	RETVAL_TEST("aeiou", "([aeiou])?|a", 5);
	RETVAL_TEST("aeiou", "([aeiou])+|a", 1);
	RETVAL_TEST("aeiou", "([aeiou])*|a", 1);
	RETVAL_TEST("1a2a3a4a5a6a", "[1-6]a", 6);
	RETVAL_TEST("1a2a3a4a5a6a", "[1-3]a", 3);
	RETVAL_TEST("1a2b3c4d5e6f", "[123456][abcdef]", 6);
	RETVAL_TEST("1a2b3c4d5e6f", "[123][abcdef]", 3);
	RETVAL_TEST(".b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b", "[:.]",  20);
	RETVAL_TEST(".b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b", "[:.b]",  40);
	RETVAL_TEST("abababababababababababababababababababab", "(a[ab])" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "([ab]a)" , 19);
	RETVAL_TEST("abababababababababababababababababababab", "(:a[ab])" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "([ab]:a)" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "([ab]{5}:a{5})" , 4);
	RETVAL_TEST("()<>[]{}*?+", "[:(:):<:>:[:]:{:}:*:?:+]", 11);
	RETVAL_TEST("()<>[]|{}*#@?+", "[()<>:[:]|{}*?+#@]", 14);
	RETVAL_TEST("12)", "#^:b*(-|:+|(:d+|:a+)[.)])", 1);
	RETVAL_TEST("12.", "#^:b*(-|:+|(:d+|:a+)[.)])", 1);
	RETVAL_TEST("a)" , "#^:b*(-|:+|(:d+|:a+)[.)])", 1);
	RETVAL_TEST("a." , "#^:b*(-|:+|(:d+|:a+)[.)])", 1);
	RETVAL_TEST("-"  , "#^:b*(-|:+|(:d+|:a+)[.)])", 1);
	RETVAL_TEST("+"  , "#^:b*(-|:+|(:d+|:a+)[.)])", 1);

	RETVAL_TEST(")>}", "[)>}]", 3);

	RETVAL_TEST("",  "[^a]",  0);
	RETVAL_TEST("a", "[^1]",  1);
	RETVAL_TEST("a", "[^a]",  0);
	RETVAL_TEST("A", "[^a]",  1);
	RETVAL_TEST("1", "[^1]",  0);
	RETVAL_TEST("1", "[^A]",  1);
	RETVAL_TEST("a", "[^:a]", 0);
	RETVAL_TEST("A", "[^:A]", 1);
	RETVAL_TEST("aaa", "[^z]", 3);
	RETVAL_TEST("a", "[^z][^z][^z]", 0);
	RETVAL_TEST("a aaa aaa", "[^ ]", 7);
	RETVAL_TEST("a aaa aaa", "[^ a]", 0);
	RETVAL_TEST("a aaa aaa", "[^:d]", 9);
	RETVAL_TEST("a aaa aaa", "[^:d:s]", 7);
	RETVAL_TEST("a aaa aaa", "[^:d:s][^:d:s][^:d:s]", 2);
	RETVAL_TEST("a aaa aaa", "[^:d:s]aa", 2);
	RETVAL_TEST("a aaa aaa", "aa[^:d:s]", 2);
	RETVAL_TEST("Raptor Test", "[^:d:s]a", 1);
	RETVAL_TEST("Raptor Test", "[^A-Z]t", 2);
	RETVAL_TEST("Raptor Test", "[^:s]z", 0);
	RETVAL_TEST("Raptor Test", "a[^ ]", 1);
	RETVAL_TEST("Raptor Test", " [^t]", 1);
	RETVAL_TEST("Raptor Test", "z[^a]", 0);
	RETVAL_TEST("a", "[^z]?", 1);
	RETVAL_TEST("a", "[^z]+", 1);
	RETVAL_TEST("a", "[^z]*", 1);
	RETVAL_TEST("a", "[^z]{1}", 1);
	RETVAL_TEST("a aaa aaa", "[^ ]?", 9);
	RETVAL_TEST("a aaa aaa", "[^ ]+", 3);
	RETVAL_TEST("a aaa aaa", "[^ ]*", 5);
	RETVAL_TEST("a aaa aaa", "[^ ]{1}", 7);
	RETVAL_TEST("a", "a[^ ]?", 1);
	RETVAL_TEST("a", "a[^ ]+", 0);
	RETVAL_TEST("a", "a[^ ]*", 1);
	RETVAL_TEST("a", "a[^ ]{1}", 0);
	RETVAL_TEST("aeiou", "a|[^ ]", 5);
	RETVAL_TEST("aeiou", "a|[^ ]?", 5);
	RETVAL_TEST("aeiou", "a|[^ ]+", 2);
	RETVAL_TEST("aeiou", "a|[^ ]*", 2);
	RETVAL_TEST("aeiou", "[^ ]|a", 5);
	RETVAL_TEST("aeiou", "[^ ]?|a", 5);
	RETVAL_TEST("aeiou", "[^ ]+|a", 1);
	RETVAL_TEST("aeiou", "[^ ]*|a", 1);
	RETVAL_TEST("aeiou", "(a|[^ ])", 5);
	RETVAL_TEST("aeiou", "(a|[^ ]?)", 5);
	RETVAL_TEST("aeiou", "(a|[^ ]+)", 2);
	RETVAL_TEST("aeiou", "(a|[^ ]*)", 2);
	RETVAL_TEST("aeiou", "([^ ]|a)", 5);
	RETVAL_TEST("aeiou", "([^ ]?|a)", 5);
	RETVAL_TEST("aeiou", "([^ ]+|a)", 1);
	RETVAL_TEST("aeiou", "([^ ]*|a)", 1);
	RETVAL_TEST("aeiou", "a|([^ ])", 5);
	RETVAL_TEST("aeiou", "a|([^ ]?)", 5);
	RETVAL_TEST("aeiou", "a|([^ ]+)", 2);
	RETVAL_TEST("aeiou", "a|([^ ]*)", 2);
	RETVAL_TEST("aeiou", "([^ ])|a", 5);
	RETVAL_TEST("aeiou", "([^ ]?)|a", 5);
	RETVAL_TEST("aeiou", "([^ ]+)|a", 1);
	RETVAL_TEST("aeiou", "([^ ]*)|a", 1);
	RETVAL_TEST("aeiou", "a|([^ ])", 5);
	RETVAL_TEST("aeiou", "a|([^ ])?", 5);
	RETVAL_TEST("aeiou", "a|([^ ])+", 2);
	RETVAL_TEST("aeiou", "a|([^ ])*", 2);
	RETVAL_TEST("aeiou", "([^ ])|a", 5);
	RETVAL_TEST("aeiou", "([^ ])?|a", 5);
	RETVAL_TEST("aeiou", "([^ ])+|a", 1);
	RETVAL_TEST("aeiou", "([^ ])*|a", 1);
	RETVAL_TEST("1a2a3a4a5a6a", "[^:a]a", 6);
	RETVAL_TEST("1a2a3a4a5a6a", "[^4-6]a", 3);
	RETVAL_TEST("1a2b3c4d5e6f", "[^:a][^:d]", 6);
	RETVAL_TEST("1a2b3c4d5e6f", "[^4-6][^:d]", 3);
	RETVAL_TEST("abababababababababababababababababababab", "(a[^a])" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "([^a]a)" , 19);
	RETVAL_TEST("abababababababababababababababababababab", "(:a[^a])" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "([^b]:a)" , 20);
	RETVAL_TEST("abababababababababababababababababababab", "([^x]{5}:a{5})" , 4);
	RETVAL_TEST("()<>[]{}*?+", "[^:w]", 11);

	RETVAL_TEST("a aaa aaa", "[^ a]", 0);
	RETVAL_TEST("a aaa aaa", "[^:d:s]", 7);
	RETVAL_TEST("a aaa aaa", "[^:d:s][^:d:s][^:d:s]", 2);
	RETVAL_TEST("a aaa aaa", "[^:d:s]aa", 2);
	RETVAL_TEST("a aaa aaa", "aa[^:d:s]", 2);
	RETVAL_TEST("Raptor Test", "[^:d:s]a", 1);
	RETVAL_TEST("Raptor Test", "[^A-Z]t", 2);
	RETVAL_TEST("a", "a[^ ]?", 1);
	RETVAL_TEST("a", "a[^ ]+", 0);
	RETVAL_TEST("a", "a[^ ]*", 1);
	RETVAL_TEST("a", "a[^ ]{1}", 0);
	RETVAL_TEST("aeiou", "a|[^ ]", 5);
	RETVAL_TEST("aeiou", "a|[^ ]?", 5);
	RETVAL_TEST("aeiou", "a|[^ ]+", 2);
	RETVAL_TEST("aeiou", "a|[^ ]*", 2);
	RETVAL_TEST("aeiou", "[^ ]|a", 5);
	RETVAL_TEST("aeiou", "[^ ]?|a", 5);
	RETVAL_TEST("aeiou", "[^ ]+|a", 1);
	RETVAL_TEST("aeiou", "[^ ]*|a", 1);
	RETVAL_TEST("aeiou", "(a|[^ ])", 5);
	RETVAL_TEST("aeiou", "(a|[^ ]?)", 5);
	RETVAL_TEST("aeiou", "(a|[^ ]+)", 2);
	RETVAL_TEST("aeiou", "(a|[^ ]*)", 2);
	RETVAL_TEST("aeiou", "([^ ]|a)", 5);
	RETVAL_TEST("aeiou", "([^ ]?|a)", 5);
	RETVAL_TEST("aeiou", "([^ ]+|a)", 1);
	RETVAL_TEST("aeiou", "([^ ]*|a)", 1);
	RETVAL_TEST("aeiou", "a|([^ ])", 5);
	RETVAL_TEST("aeiou", "a|([^ ]?)", 5);
	RETVAL_TEST("aeiou", "a|([^ ]+)", 2);
	RETVAL_TEST("aeiou", "a|([^ ]*)", 2);
	RETVAL_TEST("aeiou", "([^ ])|a", 5);
	RETVAL_TEST("aeiou", "([^ ]?)|a", 5);
	RETVAL_TEST("aeiou", "([^ ]+)|a", 1);
	RETVAL_TEST("aeiou", "([^ ]*)|a", 1);
	RETVAL_TEST("aeiou", "a|([^ ])", 5);
	RETVAL_TEST("aeiou", "a|([^ ])?", 5);
	RETVAL_TEST("aeiou", "a|([^ ])+", 2);
	RETVAL_TEST("aeiou", "a|([^ ])*", 2);
	RETVAL_TEST("aeiou", "([^ ])|a", 5);
	RETVAL_TEST("aeiou", "([^ ])?|a", 5);
	RETVAL_TEST("aeiou", "([^ ])+|a", 1);
	RETVAL_TEST("aeiou", "([^ ])*|a", 1);

	RETVAL_TEST("",  "@1",  0);
	RETVAL_TEST("a", "@1",  0);
	RETVAL_TEST("a", "@a",  0);
	RETVAL_TEST("A", "@100", 0);
	RETVAL_TEST("1", "@1",  0);
	RETVAL_TEST("",  "[@1]",  0);
	RETVAL_TEST("a", "[@1]",  0);
	RETVAL_TEST("a", "[@a]",  1);
	RETVAL_TEST("A", "[@100]", 0);
	RETVAL_TEST("1", "[@1]",  1);
	RETVAL_TEST("@", "[@1]",  1);
	RETVAL_TEST("1@@a", "[a@1]",  4);
	RETVAL_TEST("",  "[^@1",  0);
	RETVAL_TEST("a", "[^@1]",  1);
	RETVAL_TEST("a", "[^@a]",  0);
	RETVAL_TEST("A", "[^@100]", 1);
	RETVAL_TEST("1", "[^@1]",  0);
	RETVAL_TEST("@", "[^2@]",  0);

	RETVAL_TEST("",  "(@1)",  0);
	RETVAL_TEST("a", "(@1)",  0);
	RETVAL_TEST("a", "(@a)",  0);
	RETVAL_TEST("A", "(@100)", 0);
	RETVAL_TEST("1", "(@1)",  0);
	RETVAL_TEST("",  "([@1])",  0);
	RETVAL_TEST("a", "([@1])",  0);
	RETVAL_TEST("a", "([@a])",  1);
	RETVAL_TEST("A", "([@100])", 0);
	RETVAL_TEST("1", "([@1])",  1);

	RETVAL_TEST("a", "<a>@1",  0);
	RETVAL_TEST("a", "<a>@1?", 1);
	RETVAL_TEST("a", "<a>@1*", 1);
	RETVAL_TEST("a", "<a>@1+", 0);
	RETVAL_TEST("a", "<a>@1{1}", 0);
	RETVAL_TEST("a", "<x?>@1", 0);
	RETVAL_TEST("a", "<x?>@1?", 1);
	RETVAL_TEST("a", "<x?>@1*", 1);
	RETVAL_TEST("a", "<x?>@1+", 0);
	RETVAL_TEST("aa", "<a>@1",  1);
	RETVAL_TEST("aa", "<a>@1?", 1);
	RETVAL_TEST("aa", "<a>@1+", 1);
	RETVAL_TEST("aa", "<a>@1*", 1);
	RETVAL_TEST("aa", "<a>@1{1}", 1);
	RETVAL_TEST("aaaaa", "<a>@1",  2);
	RETVAL_TEST("aaaaa", "<a>@1?", 3);
	RETVAL_TEST("aaaaa", "<a>@1+", 1);
	RETVAL_TEST("aaaaa", "<a>@1*", 1);
	RETVAL_TEST("aaaaa", "<a>@1{1}", 2);

	RETVAL_TEST("a-a", "<a|:d|o_O!>-@1",  1);
	RETVAL_TEST("1-1", "<a|:d|o_O!>-@1", 1);
	RETVAL_TEST("o_O!-o_O!", "<a|:d|o_O!>-@1", 1);

	RETVAL_TEST("ae_ea", "<a><e>_@2@1", 1);
	RETVAL_TEST("ae_ea", "<<a><e>>_@2@1", 0);
	RETVAL_TEST("ae_aae", "<<a><e>>_@2@1", 1);
	RETVAL_TEST("ae_eaae_ea", "<a><e>_@2@1", 2);
	RETVAL_TEST("ae_eaae_ea", "<<a><e>>_@2@1", 0);
	RETVAL_TEST("ae_aaeae_aae", "<<a><e>>_@2@1", 2);
	RETVAL_TEST("ae_aaeae_aa1", "<<a><e>>_@2@1", 1);

	RETVAL_TEST("aaaaa", "@1<a>", 0);
	RETVAL_TEST("aaaaa", "@1<a>|<a>", 3);
	RETVAL_TEST("xxaxa", "@1<a>|<x>", 3);
	RETVAL_TEST("xxax", "@1<a>|<x>", 3);
	RETVAL_TEST("x1xax", "@1<a>|<x>1", 2);
	RETVAL_TEST("x1xaxa", "@1<a>|<x>1", 2);
	RETVAL_TEST("x1xaaa", "@1<a>|<x>1", 3);

	RETVAL_TEST("012345678910_012345678910_012345678910", "<0><1><2><3><4><5><6><7><8><9><10>_<@1@2@3@4@5@6@7@8@9@10@11>_@12", 1);
	RETVAL_TEST("012345678910_012345678910_012345678919", "<0><1><2><3><4><5><6><7><8><9><10>_<@1@2@3@4@5@6@7@8@9@10@11>_@12", 0);

	RETVAL_TEST("a", "a?#*", 1);
	RETVAL_TEST("a", "b?#*", 1);
	RETVAL_TEST("a", "a+#*", 1);
	RETVAL_TEST("a", "a*#*", 1);
	RETVAL_TEST("a", "b*#*", 1);
	RETVAL_TEST("aaa", "a+#*", 1);
	RETVAL_TEST("aaa", "a*#*", 1);
	RETVAL_TEST("aaa", "a+#*", 1);
	RETVAL_TEST("aaa", "a?#*", 3);
	RETVAL_TEST("aaab", "a+#*", 1);
	RETVAL_TEST("aaab", "a*#*", 2);
	RETVAL_TEST("aaab", "a?#*", 4);
	RETVAL_TEST("aaab", "a+#*?^$~b", 1);
	RETVAL_TEST("aaab", "a*#*?^$~b", 1);
	RETVAL_TEST("aaab", "a?#*?^$~b", 1);
	RETVAL_TEST("aaab", "a+#*?^$~b?", 1);
	RETVAL_TEST("aaab", "a*#*?^$~b?", 1);
	RETVAL_TEST("aaab", "a?#*?^$~b?", 3);
	RETVAL_TEST("aaab", "a+#*?^$~b+", 1);
	RETVAL_TEST("aaab", "a*#*?^$~b+", 1);
	RETVAL_TEST("aaab", "a?#*?^$~b+", 1);
	RETVAL_TEST("aaab", "a+#*?^$~b*", 1);
	RETVAL_TEST("aaab", "a*#*?^$~b*", 1);
	RETVAL_TEST("aaab", "a?#*?^$~b*", 3);

	RETVAL_TEST("a", "a#*", 1);
	RETVAL_TEST("a", "A#*", 1);
	RETVAL_TEST("a", "#*A", 1);
	RETVAL_TEST("a", "#*a", 1);
	RETVAL_TEST("a", "#*(A)", 1);
	RETVAL_TEST("a", "#*(a)", 1);
	RETVAL_TEST("a", "#*[A]", 1);
	RETVAL_TEST("a", "#*[a]", 1);
	RETVAL_TEST("a", "(a)#*", 1);
	RETVAL_TEST("a", "(A)#*", 1);
	RETVAL_TEST("a", "[a]#*", 1);
	RETVAL_TEST("a", "[A]#*", 1);
	RETVAL_TEST("a", "#*[A-Z]", 1);
	RETVAL_TEST("a", "[A-Z]#*", 1);

	RETVAL_TEST("aAaA", "a#*", 4);
	RETVAL_TEST("aAaA", "A#*", 4);
	RETVAL_TEST("aAaA", "#*A", 4);
	RETVAL_TEST("aAaA", "#*a", 4);
	RETVAL_TEST("aAaA", "#*(A)", 4);
	RETVAL_TEST("aAaA", "#*(a)", 4);
	RETVAL_TEST("aAaA", "#*[A]", 4);
	RETVAL_TEST("aAaA", "#*[a]", 4);
	RETVAL_TEST("aAaA", "(a)#*", 4);
	RETVAL_TEST("aAaA", "(A)#*", 4);
	RETVAL_TEST("aAaA", "[a]#*", 4);
	RETVAL_TEST("aAaA", "[A]#*", 4);
	RETVAL_TEST("aAaA", "#*[A-Z]", 4);
	RETVAL_TEST("aAaA", "[A-Z]#*", 4);
	RETVAL_TEST("aAaA", "(a#*)", 4);
	RETVAL_TEST("aAaA", "(A#*)", 4);
	RETVAL_TEST("aAaA", "(a)#*", 4);
	RETVAL_TEST("aAaA", "(A)#*", 4);
	RETVAL_TEST("aAbB", "#*a|b", 4);
	RETVAL_TEST("aAbB", "#*A|B", 4);
	RETVAL_TEST("aAbB", "#*(a|b)", 4);
	RETVAL_TEST("aAbB", "#*(A|B)", 4);
	RETVAL_TEST("aAbB", "(a#*|b#*)", 4);
	RETVAL_TEST("aAbB", "(A#*|B#*)", 4);
	RETVAL_TEST("aAbB", "(a|b)#*", 4);
	RETVAL_TEST("aAbB", "(A|B)#*", 4);
	RETVAL_TEST("TesT", "test", 0);
	RETVAL_TEST("TesT", "test#*", 0);
	RETVAL_TEST("TesT", "t#*est#*", 1);
	RETVAL_TEST("TesT", "#*test", 1);
	RETVAL_TEST("TesT", "#*tESt", 1);
	RETVAL_TEST("TesT", "#*(tESt)", 1);
	RETVAL_TEST("TesT", "(tESt)#*", 1);

	RETVAL_TEST("Raptor TesT Fest", "RapTor (tESt)#* fEST", 0);
	RETVAL_TEST("Raptor TesT Fest", "#*rapTor (tESt) fEST", 1);
	RETVAL_TEST("Raptor TesT Fest", "(RapTor)#* (tESt)#* (fEST)#*", 1);
	RETVAL_TEST("Raptor TesT Fest", "((Rap#*Tor)#* (t#*ESt)#* (fEST)#*)#*", 1);
	RETVAL_TEST("Raptor TesT Fest", "#*[a-z]#*apTor (tESt) [A-Z]#*EST", 1);

	RETVAL_TEST("a", "a#/", 1);
	RETVAL_TEST("a", "A#/", 0);
	RETVAL_TEST("a", "#/A", 0);
	RETVAL_TEST("a", "#/a", 1);
	RETVAL_TEST("a", "#/(A)", 0);
	RETVAL_TEST("a", "#/(a)", 1);
	RETVAL_TEST("a", "#/[A]", 0);
	RETVAL_TEST("a", "#/[a]", 1);
	RETVAL_TEST("a", "#/A-Z", 0);
	RETVAL_TEST("a", "A-Z#/", 0);
	RETVAL_TEST("a", "(a)#/", 1);
	RETVAL_TEST("a", "(A)#/", 0);
	RETVAL_TEST("a", "[a]#/", 1);
	RETVAL_TEST("a", "[A]#/", 0);
	RETVAL_TEST("a", "#/[A-Z]", 0);
	RETVAL_TEST("a", "[A-Z]#/", 0);

	RETVAL_TEST("aAaA", "a#/", 2);
	RETVAL_TEST("aAaA", "A#/", 2);
	RETVAL_TEST("aAaA", "#/A", 2);
	RETVAL_TEST("aAaA", "#/a", 2);
	RETVAL_TEST("aAaA", "#/(A)", 2);
	RETVAL_TEST("aAaA", "#/(a)", 2);
	RETVAL_TEST("aAaA", "#/[A]", 2);
	RETVAL_TEST("aAaA", "#/[a]", 2);
	RETVAL_TEST("aAaA", "(a)#/", 2);
	RETVAL_TEST("aAaA", "(A)#/", 2);
	RETVAL_TEST("aAaA", "[a]#/", 2);
	RETVAL_TEST("aAaA", "[A]#/", 2);
	RETVAL_TEST("aAaA", "#/[A-Z]", 2);
	RETVAL_TEST("aAaA", "[A-Z]#/", 2);
	RETVAL_TEST("aAaA", "(a#/)", 2);
	RETVAL_TEST("aAaA", "(A#/)", 2);
	RETVAL_TEST("aAaA", "(a)#/", 2);
	RETVAL_TEST("aAaA", "(A)#/", 2);
	RETVAL_TEST("aAbB", "#/a|b", 2);
	RETVAL_TEST("aAbB", "#/A|B", 2);
	RETVAL_TEST("aAbB", "#/(a|b)", 2);
	RETVAL_TEST("aAbB", "#/(A|B)", 2);
	RETVAL_TEST("aAbB", "(a#/|b#/)", 2);
	RETVAL_TEST("aAbB", "(A#/|B#/)", 2);
	RETVAL_TEST("aAbB", "(a|b)#/", 2);
	RETVAL_TEST("aAbB", "(A|B)#/", 2);

	RETVAL_TEST("Raptor TesT Fest", "#*rapTor (tESt)#/ fEST", 0);
	RETVAL_TEST("Raptor tESt Fest", "#*rapTor (tESt)#/ fEST", 1);
	RETVAL_TEST("Raptor TesT Fest", "#*rapTor (tE#/S#/t)#* fEST", 0);
	RETVAL_TEST("Raptor tESt Fest", "#*rapTor (tE#/S#/t)#* fEST", 1);
	RETVAL_TEST("31-13-1331", "<0?[1-9]|[12][0-9]|3[01]>[/:-\\]<0?[1-9]|1[012]>[/:-\\]<[12][0-9]{3}>", 0);
	RETVAL_TEST("71-17-1177", "<0?[1-9]|[12][0-9]|3[01]>[/:-\\]<0?[1-9]|1[012]>[/:-\\]<[12][0-9]{3}>", 0);
	RETVAL_TEST("31/13-1331", "<0?[1-9]|[12][0-9]|3[01]><[/:-\\]><0?[1-9]|1[012]>@2<[12][0-9]{3}>", 0);
	RETVAL_TEST("71-17/1177", "<0?[1-9]|[12][0-9]|3[01]><[/:-\\]><0?[1-9]|1[012]>@2<[12][0-9]{3}>", 0);
}

static void fetch(ut_runner *r)
{

	FETCH_TEST("a", "<a>", 1, "a");
	FETCH_TEST("aa", "<aa>", 1, "aa");
	FETCH_TEST("a a a", "<a>", 3, "a");
	FETCH_TEST("abcd", "<a|b|c|d>", 1, "a");
	FETCH_TEST("abcd", "<a|b|c|d>", 2, "b");
	FETCH_TEST("abcd", "<a|b|c|d>", 3, "c");
	FETCH_TEST("abcd", "<a|b|c|d>", 4, "d");
	FETCH_TEST("abcd", "<a|b|c|d>", 5, "");
	FETCH_TEST("abc", "a<x>", 1, "");
	FETCH_TEST("abc", "<a>x", 1, "");
	FETCH_TEST("abc", "<a|b>x", 1, "");
	FETCH_TEST("abc", "<<a|b>x|abc>", 1, "abc");
	FETCH_TEST("abc", "<<a|b>x|abc>", 2, "");
	FETCH_TEST("abc", "<x<a|b>|abc>", 1, "abc");
	FETCH_TEST("abc", "<x<a|b>|abc>", 2, "");
	FETCH_TEST("abc bca cab", "<a|b|c>", 9, "b");
	FETCH_TEST("abc bca cab", "<(a|b|c)(a|b|c)(a|b|c)>", 3, "cab");
	FETCH_TEST("abc bca cab", "<(a|b|c)(a|b|c)(a|b|c)> ", 2, "bca");
	FETCH_TEST("abc bca cab", "#?<(a|b|c)(a|b|c)(a|b|c)>", 1, "abc");
	FETCH_TEST("abc bca abc", "#?<(a|b|c)(a|b|c)(x)>", 1, "");
	FETCH_TEST("abc bca abx", "#?<(a|b|c)(a|b|c)(x)>", 1, "abx");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 1, "abc");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 2, "iec");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 3, "i");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 4, "c");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 5, "oeb");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 6, "o");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 7, "b");
	FETCH_TEST("abc iecc oeb", "<<(a|e)|(i|o)>e<b|c>|abc>", 8, "");

	FETCH_TEST("a", "<a>?", 1, "a");
	FETCH_TEST("a", "<b>?", 1, "");
	FETCH_TEST("a", "<a>+", 1, "a");
	FETCH_TEST("a", "<a>*", 1, "a");
	FETCH_TEST("a", "<b>*", 1, "");
	FETCH_TEST("aaa", "<a>+", 1, "aaa");
	FETCH_TEST("aaa", "<a>*", 1, "aaa");
	FETCH_TEST("aaa", "#~<a>+", 1, "aaa");
	FETCH_TEST("aaa", "#~<a>*", 1, "aaa");
	FETCH_TEST("aaab", "#~<a+>", 1, "aaa");
	FETCH_TEST("aaab", "#~<a*>", 1, "aaa");
	FETCH_TEST("aaab", "#~<a?>", 4, "");
	FETCH_TEST("aaab", "#~<a+b>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a*b>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a?b>", 1, "ab");
	FETCH_TEST("aaab", "#~<a+b?>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a*b?>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a?b?>", 3, "ab");
	FETCH_TEST("aaab", "#~<a+b+>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a*b+>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a?b+>", 1, "ab");
	FETCH_TEST("aaab", "#~<a+b*>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a*b*>", 1, "aaab");
	FETCH_TEST("aaab", "#~<a?b*>", 3, "ab");
	FETCH_TEST("aaabaaa", "#~<a+>", 4, "aaa");
	FETCH_TEST("aaabaaa", "#~<a*>", 5, "aaa");

	FETCH_TEST("Raptor Test",     "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1, "Raptor Test");
	FETCH_TEST("Raptor Test",     "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 2, "T");
	FETCH_TEST("Raaaaptor TFest", "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1, "Raaaaptor TFest");
	FETCH_TEST("Raaaaptor TFest", "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 2, "TF");
	FETCH_TEST("CaptorTest",      "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1, "CaptorTest");
	FETCH_TEST("Cap CaptorTest",  "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1, "Cap CaptorTest");
	FETCH_TEST("Cap CaptorTest",  "#~<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 3, "CaptorTest");
	FETCH_TEST("Rap Captor Fest", "<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 1, "Rap Captor Fest");
	FETCH_TEST("Rap Captor Fest", "#~<((C|R)ap C|C|R)(a+p{1}tor) ?((<T|F>+e)(st))>", 3, "Captor Fest");
}

static void put(ut_runner *r)
{

	PUT_TEST("a", "<a>", "#1", "a");
	PUT_TEST("a", "<a>", "#x", "x");
	PUT_TEST("a", "<a>", "#xx", "xx");
	PUT_TEST("a", "<a>", "###1##", "#a#");
	PUT_TEST("a", "<a>", "[#0][#1][#2#3#1000000]", "[][a][]");
	PUT_TEST("aa", "<aa>", "#1", "aa");
	PUT_TEST("a a a", "<a>", "#1#2#3", "aaa");
	PUT_TEST("abcd", "<a|b|c|d>", "#4 #3 #2 #1", "d c b a");
	PUT_TEST("1 2 3 4 5 6 7 8 9", "<1|2|3|4|5|6|7|8|9>", "#5 #6 #7 #8 #9 #1 #2 #3 #4", "5 6 7 8 9 1 2 3 4");
	PUT_TEST("1 2 3 4 5 6 7 8 9", "<1>|<2>|<3>|<4>|<5>|<6>|<7>|<8>|<9>", "#5 #6 #7 #8 #9 #1 #2 #3 #4", "5 6 7 8 9 1 2 3 4");
	PUT_TEST("Raptor Test", "<aptor|est>", "C#1 F#2", "Captor Fest");
	PUT_TEST("Raptor Test", "<aptor|est>", "C#5 F#2", "C Fest");
	PUT_TEST("Raptor Test", "<aptor|est>", "C#a F#2", "Ca Fest");
	PUT_TEST("Raptor Test", "<aptor|est>", "C#0 F#2", "C Fest");
	PUT_TEST("Raptor Test", "<aptor|est>", "C#43 F#43", "C F");
	PUT_TEST("Raptor Test", "<aptor|est>", "C##43 ##F#43##", "C#43 #F#");
	PUT_TEST("Raptor Test", "<aptor|est>", "C##43 ##1##2", "C#43 #1#2");
	PUT_TEST("Raptor Test", "<aptor|est>", "##Raptor ##Test", "#Raptor #Test");
	PUT_TEST("Raptor Test Fest", "<Raptor> <Test>", "#1_#2", "Raptor_Test");
	PUT_TEST("..figure > test figure", "#^<:s*:.:.>:s*<[:w:-:_]+><[^:>]*>:>:s*<.*>", "[#1][#2][#3][#4]", "[..][figure][ ][test figure]")


		PUT_TEST("123456789", "#$<<:d><:d>>", "[#2] [#3] [#1]", "[8] [9] [89]");

	PUT_TEST("make a new Line", "#^<[^n]+>", "#1raptor", "make a raptor");
	PUT_TEST("07-07-1777", "<0?[1-9]|[12][0-9]|3[01]>[/:-\\]<0?[1-9]|1[012]>[/:-\\]<[12][0-9]{3}>", "d:#1 m:#2 y:#3", "d:07 m:07 y:1777");
	PUT_TEST("fecha: 07-07-1777", "<0?[1-9]|[12][0-9]|3[01]>[/:-\\]<0?[1-9]|1[012]>[/:-\\]<[12][0-9]{3}>", "d:#1 m:#2 y:#3", "d:07 m:07 y:1777");
	PUT_TEST("07-07-1777", "<0?[1-9]|[12][0-9]|3[01]><[/:-\\]><0?[1-9]|1[012]>@2<[12][0-9]{3}>", "d:#1 m:#3 y:#4", "d:07 m:07 y:1777");
	PUT_TEST("fecha: 07-07-1777", "<0?[1-9]|[12][0-9]|3[01]><[/:-\\]><0?[1-9]|1[012]>@2<[12][0-9]{3}>", "d:#1 m:#3 y:#4", "d:07 m:07 y:1777");
	PUT_TEST("nasciiboy@gmail.com", "<[_A-Za-z0-9:-]+(:.[_A-Za-z0-9:-]+)*>:@<[A-Za-z0-9]+>:.<[A-Za-z0-9]+><:.[A-Za-z0-9]{2}>*", "[#1][#2][#3]", "[nasciiboy][gmail][com]");
	PUT_TEST("<mail>nasciiboy@gmail.com</mail>", "<[_A-Za-z0-9:-]+(:.[_A-Za-z0-9:-]+)*>:@<[A-Za-z0-9]+>:.<[A-Za-z0-9]+><:.[A-Za-z0-9]{2}>*", "[#1][#2][#3]", "[nasciiboy][gmail][com]");
	PUT_TEST("u.s.r_43@ru.com.jp", "<[_A-Za-z0-9:-]+(:.[_A-Za-z0-9:-]+)*>:@<[A-Za-z0-9]+>:.<[A-Za-z0-9]+><:.[A-Za-z0-9]{2}>*", "[#1][#2][#3]", "[u.s.r_43][ru][com]");
	PUT_TEST("https://en.wikipedia.org/wiki/Regular_expression", "(https?|ftp):://<[^:s/:<:>]+></[^:s:.:<:>,/]+>*<.>*", "[#1][#2][#3]", "[en.wikipedia.org][/wiki/Regular_expression][]");
	PUT_TEST("https://en.wikipedia.org/wiki/Regular_expression.test", "(https?|ftp):://<[^:s/:<:>]+></[^:s:.:<:>,/]+>*<.>*", "[#1][#2][#3]", "[en.wikipedia.org][/wiki/Regular_expression][.test]");
	PUT_TEST("https://en.wikipedia.org/wiki/Regular_expression,test", "(https?|ftp):://<[^:s/:<:>]+></[^:s:.:<:>,/]+>*<.>*", "[#1][#2][#3]", "[en.wikipedia.org][/wiki/Regular_expression][,test]");
	PUT_TEST("<url>https://en.wikipedia.org/wiki/Regular_expression<url>", "(https?|ftp):://<[^:s/:<:>]+></[^:s:.:<:>,/]+>*<.>*", "[#1][#2][#3]", "[en.wikipedia.org][/wiki/Regular_expression][<url>]");

}

static void replace(ut_runner *r)
{
	REPLACE_TEST("a", "<a>"   , 1, "", "");
	REPLACE_TEST("a", "<a>?"  , 1, "", "");
	REPLACE_TEST("a", "<a>+"  , 1, "", "");
	REPLACE_TEST("a", "<a>*"  , 1, "", "");
	REPLACE_TEST("a", "<a>{1}", 1, "", "");
	REPLACE_TEST("a", "<a?>"  , 1, "", "");
	REPLACE_TEST("a", "<a+>"  , 1, "", "");
	REPLACE_TEST("a", "<a*>"  , 1, "", "");
	REPLACE_TEST("a", "<a{1}>", 1, "", "");

	REPLACE_TEST("a", "<a>"   , 1, "e", "e");
	REPLACE_TEST("a", "<a>?"  , 1, "e", "e");
	REPLACE_TEST("a", "<a>+"  , 1, "e", "e");
	REPLACE_TEST("a", "<a>*"  , 1, "e", "e");
	REPLACE_TEST("a", "<a>{1}", 1, "e", "e");
	REPLACE_TEST("a", "<a?>"  , 1, "e", "e");
	REPLACE_TEST("a", "<a+>"  , 1, "e", "e");
	REPLACE_TEST("a", "<a*>"  , 1, "e", "e");
	REPLACE_TEST("a", "<a{1}>", 1, "e", "e");

	REPLACE_TEST("a", "<x>"   , 1, "z", "a");
	REPLACE_TEST("a", "<x>?"  , 1, "z", "za");
	REPLACE_TEST("a", "<x>+"  , 1, "z", "a");
	REPLACE_TEST("a", "<x>*"  , 1, "z", "za");
	REPLACE_TEST("a", "<x>{1}", 1, "z", "a");
	REPLACE_TEST("a", "<x?>"  , 1, "z", "za");
	REPLACE_TEST("a", "<x+>"  , 1, "z", "a");
	REPLACE_TEST("a", "<x*>"  , 1, "z", "za");
	REPLACE_TEST("a", "<x{1}>", 1, "z", "a");

	REPLACE_TEST("aaa", "<a>"   , 1, "", "");
	REPLACE_TEST("aaa", "<a>?"  , 1, "", "");
	REPLACE_TEST("aaa", "<a>+"  , 1, "", "");
	REPLACE_TEST("aaa", "<a>*"  , 1, "", "");
	REPLACE_TEST("aaa", "<a>{1}", 1, "", "");
	REPLACE_TEST("aaa", "<a?>"  , 1, "", "");
	REPLACE_TEST("aaa", "<a+>"  , 1, "", "");
	REPLACE_TEST("aaa", "<a*>"  , 1, "", "");
	REPLACE_TEST("aaa", "<a{1}>", 1, "", "");

	REPLACE_TEST("aaa", "<a>"   , 1, "e", "eee");
	REPLACE_TEST("aaa", "<a>?"  , 1, "e", "eee");
	REPLACE_TEST("aaa", "<a>+"  , 1, "e", "e");
	REPLACE_TEST("aaa", "<a>*"  , 1, "e", "e");
	REPLACE_TEST("aaa", "<a>{1}", 1, "e", "eee");
	REPLACE_TEST("aaa", "<a?>"  , 1, "e", "eee");
	REPLACE_TEST("aaa", "<a+>"  , 1, "e", "e");
	REPLACE_TEST("aaa", "<a*>"  , 1, "e", "e");
	REPLACE_TEST("aaa", "<a{1}>", 1, "e", "eee");

	REPLACE_TEST("aaa", "<x>"   , 1, "z", "aaa");
	REPLACE_TEST("aaa", "<x>?"  , 1, "z", "zazaza");
	REPLACE_TEST("aaa", "<x>+"  , 1, "z", "aaa");
	REPLACE_TEST("aaa", "<x>*"  , 1, "z", "zazaza");
	REPLACE_TEST("aaa", "<x>{1}", 1, "z", "aaa");
	REPLACE_TEST("aaa", "<x?>"  , 1, "z", "zazaza");
	REPLACE_TEST("aaa", "<x+>"  , 1, "z", "aaa");
	REPLACE_TEST("aaa", "<x*>"  , 1, "z", "zazaza");
	REPLACE_TEST("aaa", "<x{1}>", 1, "z", "aaa");

	REPLACE_TEST("aaab", "<a>"   , 1, "e", "eeeb");
	REPLACE_TEST("aaab", "<a>?"  , 1, "e", "eeeeb");
	REPLACE_TEST("aaab", "<a>+"  , 1, "e", "eb");
	REPLACE_TEST("aaab", "<a>*"  , 1, "e", "eeb");
	REPLACE_TEST("aaab", "<a>{1}", 1, "e", "eeeb");
	REPLACE_TEST("aaab", "<a?>"  , 1, "e", "eeeeb");
	REPLACE_TEST("aaab", "<a+>"  , 1, "e", "eb");
	REPLACE_TEST("aaab", "<a*>"  , 1, "e", "eeb");
	REPLACE_TEST("aaab", "<a{1}>", 1, "e", "eeeb");

	REPLACE_TEST("aaab", "<x>"   , 1, "z", "aaab");
	REPLACE_TEST("aaab", "<x>?"  , 1, "z", "zazazazb");
	REPLACE_TEST("aaab", "<x>+"  , 1, "z", "aaab");
	REPLACE_TEST("aaab", "<x>*"  , 1, "z", "zazazazb");
	REPLACE_TEST("aaab", "<x>{1}", 1, "z", "aaab");
	REPLACE_TEST("aaab", "<x?>"  , 1, "z", "zazazazb");
	REPLACE_TEST("aaab", "<x+>"  , 1, "z", "aaab");
	REPLACE_TEST("aaab", "<x*>"  , 1, "z", "zazazazb");
	REPLACE_TEST("aaab", "<x{1}>", 1, "z", "aaab");

	REPLACE_TEST("aaabaaa", "<a>"   , 1, "e", "eeebeee");
	REPLACE_TEST("aaabaaa", "<a>?"  , 1, "e", "eeeebeee");
	REPLACE_TEST("aaabaaa", "<a>+"  , 1, "e", "ebe");
	REPLACE_TEST("aaabaaa", "<a>*"  , 1, "e", "eebe");
	REPLACE_TEST("aaabaaa", "<a>{1}", 1, "e", "eeebeee");
	REPLACE_TEST("aaabaaa", "<a?>"  , 1, "e", "eeeebeee");
	REPLACE_TEST("aaabaaa", "<a+>"  , 1, "e", "ebe");
	REPLACE_TEST("aaabaaa", "<a*>"  , 1, "e", "eebe");
	REPLACE_TEST("aaabaaa", "<a{1}>", 1, "e", "eeebeee");

	REPLACE_TEST("aaabaaa", "<x>"   , 1, "z", "aaabaaa");
	REPLACE_TEST("aaabaaa", "<x>?"  , 1, "z", "zazazazbzazaza");
	REPLACE_TEST("aaabaaa", "<x>+"  , 1, "z", "aaabaaa");
	REPLACE_TEST("aaabaaa", "<x>*"  , 1, "z", "zazazazbzazaza");
	REPLACE_TEST("aaabaaa", "<x>{1}", 1, "z", "aaabaaa");
	REPLACE_TEST("aaabaaa", "<x?>"  , 1, "z", "zazazazbzazaza");
	REPLACE_TEST("aaabaaa", "<x+>"  , 1, "z", "aaabaaa");
	REPLACE_TEST("aaabaaa", "<x*>"  , 1, "z", "zazazazbzazaza");
	REPLACE_TEST("aaabaaa", "<x{1}>", 1, "z", "aaabaaa");

	REPLACE_TEST("aaabaaa aaabaaa", "<a><b>"   , 1, "e", "aaebaaa aaebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a>?<b>"  , 1, "e", "aaebaaa aaebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a>+<b>"  , 1, "e", "ebaaa ebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a>*<b>"  , 1, "e", "ebaaa ebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a>{1}<b>", 1, "e", "aaebaaa aaebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a?><b>"  , 1, "e", "aaebaaa aaebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a+><b>"  , 1, "e", "ebaaa ebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a*><b>"  , 1, "e", "ebaaa ebaaa");
	REPLACE_TEST("aaabaaa aaabaaa", "<a{1}><b>", 1, "e", "aaebaaa aaebaaa");

	REPLACE_TEST("Raptor Test", "<Raptor>", 1, "Captor", "Captor Test");
	REPLACE_TEST("Raptor Test", "<Raptor>", 0, "Captor", "Raptor Test");
	REPLACE_TEST("Raptor Test", "<Raptor|Test>", 0, "Captor", "Raptor Test");
	REPLACE_TEST("Raptor Test", "<Raptor|Test>", 1, "Captor", "Captor Captor");
	REPLACE_TEST("Raptor Test", "<Raptor|Test>", 2, "Captor", "Raptor Test");
	REPLACE_TEST("Raptor Test", "<Raptor|<Test>>", 2, "Fest", "Raptor Fest");
	REPLACE_TEST("Raptor Raptors Raptoring", "<Raptor:w*>", 1, "Test", "Test Test Test");
	REPLACE_TEST("Raptor Raptors Raptoring", "<Raptor>:w*", 1, "Test", "Test Tests Testing");
	REPLACE_TEST("Raptor Raptors Raptoring", "<<<R>a>ptor>:w*", 3, "C", "Captor Captors Captoring");
	REPLACE_TEST("Raptor Raptors Raptoring", "<<<R>a>ptor>:w*", 2, "4", "4ptor 4ptors 4ptoring");
}

static void test_utf8(ut_runner *r)
{
	RETVAL_TEST("a", "▲", 0);
	RETVAL_TEST("a", "▲?", 1);
	RETVAL_TEST("a", "△?", 1);
	RETVAL_TEST("a", "▲+", 0);
	RETVAL_TEST("a", "▲*", 1);
	RETVAL_TEST("a", "△*", 1);
	RETVAL_TEST("▲", "▲", 1);
	RETVAL_TEST("▲", "▲?", 1);
	RETVAL_TEST("▲", "△?", 1);
	RETVAL_TEST("▲", "▲+", 1);
	RETVAL_TEST("▲", "▲*", 1);
	RETVAL_TEST("▲", "△*", 1);
	RETVAL_TEST("▲▲▲", "▲+", 1);
	RETVAL_TEST("▲▲▲", "▲*", 1);
	RETVAL_TEST("▲▲▲", "▲+", 1);
	RETVAL_TEST("▲▲▲", "▲?", 3);
	RETVAL_TEST("▲▲▲△", "▲+", 1);
	RETVAL_TEST("▲▲▲△", "▲*", 2);
	RETVAL_TEST("▲▲▲△", "▲?", 4);
	RETVAL_TEST("▲▲▲△", "▲+△", 1);
	RETVAL_TEST("▲▲▲△", "▲*△", 1);
	RETVAL_TEST("▲▲▲△", "▲?△", 1);
	RETVAL_TEST("▲▲▲△", "▲+△?", 1);
	RETVAL_TEST("▲▲▲△", "▲*△?", 1);
	RETVAL_TEST("▲▲▲△", "▲?△?", 3);
	RETVAL_TEST("▲▲▲△", "▲+△+", 1);
	RETVAL_TEST("▲▲▲△", "▲*△+", 1);
	RETVAL_TEST("▲▲▲△", "▲?△+", 1);
	RETVAL_TEST("▲▲▲△", "▲+△*", 1);
	RETVAL_TEST("▲▲▲△", "▲*△*", 1);
	RETVAL_TEST("▲▲▲△", "▲?△*", 3);
	RETVAL_TEST("▲▲▲△▲▲▲", "▲+", 2);
	RETVAL_TEST("▲▲▲△▲▲▲", "▲*", 3);
	RETVAL_TEST("▲▲▲△▲▲▲", "▲*", 3);
	RETVAL_TEST("▲▲▲△▲▲▲", "▲*", 3);
	RETVAL_TEST("▲", "(▲)?", 1);
	RETVAL_TEST("▲", "(△)?", 1);
	RETVAL_TEST("▲", "(▲)+", 1);
	RETVAL_TEST("▲", "(▲)*", 1);
	RETVAL_TEST("▲", "(△)*", 1);
	RETVAL_TEST("▲▲▲", "(▲)+", 1);
	RETVAL_TEST("▲▲▲", "(▲)*", 1);
	RETVAL_TEST("▲▲▲", "#~(▲)+", 3);
	RETVAL_TEST("▲▲▲", "#~(▲)*", 3);
	RETVAL_TEST("▲▲▲△", "#~(▲+)", 3);
	RETVAL_TEST("▲▲▲△", "#~(▲*)", 4);
	RETVAL_TEST("▲▲▲△", "#~(▲?)", 4);
	RETVAL_TEST("▲▲▲△", "#~(▲+△)", 3);
	RETVAL_TEST("▲▲▲△", "#~(▲*△)", 4);
	RETVAL_TEST("▲▲▲△", "#~(▲?△)", 2);
	RETVAL_TEST("▲▲▲△", "#~(▲+△?)", 3);
	RETVAL_TEST("▲▲▲△", "#~(▲*△?)", 4);
	RETVAL_TEST("▲▲▲△", "#~(▲?△?)", 4);
	RETVAL_TEST("▲▲▲△", "#~(▲+△+)", 3);
	RETVAL_TEST("▲▲▲△", "#~(▲*△+)", 4);
	RETVAL_TEST("▲▲▲△", "#~(▲?△+)", 2);
	RETVAL_TEST("▲▲▲△", "#~(▲+△*)", 3);
	RETVAL_TEST("▲▲▲△", "#~(▲*△*)", 4);
	RETVAL_TEST("▲▲▲△", "#~(▲?△*)", 4);
	RETVAL_TEST("▲▲▲△▲▲▲", "#~(▲+)", 6);
	RETVAL_TEST("▲▲▲△▲▲▲", "#~(▲*)", 7);
	RETVAL_TEST("▲", "[▲]?", 1);
	RETVAL_TEST("▲", "[△]?", 1);
	RETVAL_TEST("▲", "[▲]+", 1);
	RETVAL_TEST("▲", "[▲]*", 1);
	RETVAL_TEST("▲", "[△]*", 1);
	RETVAL_TEST("▲▲▲", "[▲]?", 3);
	RETVAL_TEST("▲▲▲", "[▲]+", 1);
	RETVAL_TEST("▲▲▲", "[▲]*", 1);
	RETVAL_TEST("▲▲▲", "#~[▲]?", 3);
	RETVAL_TEST("▲▲▲", "#~[▲]+", 3);
	RETVAL_TEST("▲▲▲", "#~[▲]*", 3);
	RETVAL_TEST("▲▲▲△", "#~[▲△]", 4);
	RETVAL_TEST("▲▲▲△", "#~[▲△]?", 4);
	RETVAL_TEST("▲▲▲△", "#~[▲△]+", 4);
	RETVAL_TEST("▲▲▲△", "#~[▲△]*", 4);
	RETVAL_TEST("▲▲▲△▲▲▲", "#~[▲△]", 7);
	RETVAL_TEST("▲", ":&", 1);
	RETVAL_TEST("▲", ":&?", 1);
	RETVAL_TEST("▲", ":&+", 1);
	RETVAL_TEST("▲", ":&*", 1);
	RETVAL_TEST("▲▲▲", ":&?", 3);
	RETVAL_TEST("▲▲▲", ":&+", 1);
	RETVAL_TEST("▲▲▲", ":&*", 1);
	RETVAL_TEST("▲▲▲", "#~:&?", 3);
	RETVAL_TEST("▲▲▲", "#~:&+", 3);
	RETVAL_TEST("▲▲▲", "#~:&*", 3);
	RETVAL_TEST("▲▲▲△", "#~:&", 4);
	RETVAL_TEST("▲▲▲△", "#~:&?", 4);
	RETVAL_TEST("▲▲▲△", "#~:&+", 4);
	RETVAL_TEST("▲▲▲△", "#~:&*", 4);
	RETVAL_TEST("▲▲▲△▲▲▲", "#~:&", 7);
	RETVAL_TEST("▲", ":w", 0);
	RETVAL_TEST("▲", ":w?", 1);
	RETVAL_TEST("▲", ":w+", 0);
	RETVAL_TEST("▲", ":w*", 1);
	RETVAL_TEST("▲▲▲", ":w?", 3);
	RETVAL_TEST("▲▲▲", ":w+", 0);
	RETVAL_TEST("▲▲▲", ":w*", 3);
	RETVAL_TEST("▲▲▲", "#~:w?", 3);
	RETVAL_TEST("▲▲▲", "#~:w+", 0);
	RETVAL_TEST("▲▲▲", "#~:w*", 3);
	RETVAL_TEST("▲▲▲△", "#~:w", 0);
	RETVAL_TEST("▲▲▲△", "#~:w?", 4);
	RETVAL_TEST("▲▲▲△", "#~:w+", 0);
	RETVAL_TEST("▲▲▲△", "#~:w*", 4);
	RETVAL_TEST("▲▲▲△▲▲▲", "#~:w", 0);
	RETVAL_TEST("▲", ":W", 1);
	RETVAL_TEST("▲", ":W?", 1);
	RETVAL_TEST("▲", ":W+", 1);
	RETVAL_TEST("▲", ":W*", 1);
	RETVAL_TEST("▲▲▲", ":W?", 3);
	RETVAL_TEST("▲▲▲", ":W+", 1);
	RETVAL_TEST("▲▲▲", ":W*", 1);
	RETVAL_TEST("▲▲▲", "#~:W?", 3);
	RETVAL_TEST("▲▲▲", "#~:W+", 3);
	RETVAL_TEST("▲▲▲", "#~:W*", 3);
	RETVAL_TEST("▲▲▲△", "#~:W", 4);
	RETVAL_TEST("▲▲▲△", "#~:W?", 4);
	RETVAL_TEST("▲▲▲△", "#~:W+", 4);
	RETVAL_TEST("▲▲▲△", "#~:W*", 4);
	RETVAL_TEST("▲▲▲△▲▲▲", "#~:W", 7);

	RETVAL_TEST("△▲3△567△9", ".", 9);
	RETVAL_TEST("△▲3△567△9", "(.)", 9);
	RETVAL_TEST("△▲3△567△9", "[.]", 0);
	RETVAL_TEST("△▲3△567△9", "(.+)", 1);
	RETVAL_TEST("△▲3△567△9", ":&", 4);
	RETVAL_TEST("△▲3△567△9", ":w", 5);
	RETVAL_TEST("△▲3△567△9", ":W", 4);
	RETVAL_TEST("△▲3△567△9", ":d", 5);
	RETVAL_TEST("△▲3△567△9", ":a", 0);
	RETVAL_TEST("△▲3△567△9", "[3-9]", 5);
	RETVAL_TEST("△▲3△567△9", "[^3-9]", 4);
	RETVAL_TEST("△▲3△567△9", "[^a-z]", 9);
	RETVAL_TEST("△▲3△567△9", "[^:d]", 4);
	RETVAL_TEST("△▲3△567△9", "[^:D]", 5);
	RETVAL_TEST("△▲3△567△9", "[^:w]", 4);
	RETVAL_TEST("△▲3△567△9", "[^:W]", 5);
	RETVAL_TEST("△▲3△567△9", "[^:&]", 5);
	RETVAL_TEST("△▲3△567△9", "[^:a]", 9);
	RETVAL_TEST("△▲3△567△9", "[^:A]", 0);



	RETVAL_TEST("Rááptor Test", "R.áptor", 1);
	RETVAL_TEST("Rááptor Test", "Rá{2}ptor", 1);
	RETVAL_TEST("Rááptor Test", "R(á){2}ptor", 1);
	RETVAL_TEST("R△△△ptor Test", "R△{3}ptor", 1);
	RETVAL_TEST("R△△△ptor Test", "R[^a]{3}ptor", 1);
	RETVAL_TEST("R▲△ptor Test", "R[△▲]{2}ptor", 1);
	RETVAL_TEST("R▲△ptor Test", "R[^ae]{2}ptor", 1);
	RETVAL_TEST("R▲△ptor Test", "R.{2}ptor", 1);
	RETVAL_TEST("R▲△ptor Test", "R[:W]{2}ptor", 1);
	RETVAL_TEST("R▲△ptor Test", "R[^:w]{2}ptor", 1);

}


void regex_test_init(ut_suite *s)
{
	ut_suite_init(s, "suite1");
	ut_suite_add(s, retcode);
	ut_suite_add(s, fetch);
	ut_suite_add(s, put);
	ut_suite_add(s, replace);
	ut_suite_add(s, test_utf8);
}
